apiVersion: apps/v1
kind: Deployment
metadata:
  name: flutter-web-deployment
  labels:
    app: flutter-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flutter-web
  template:
    metadata:
      labels:
        app: flutter-web
    spec:
      containers:
        - name: flutter-web-container
          image: flutter-web-kubernetes
          imagePullPolicy: Never
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: flutter-web-service
spec:
  selector:
    app: flutter-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
