kind: Cluster
apiVersion: kind.x.k8s.io/v1beta1
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 6443
        hostPort: 6443
        protocol: TCP
      - containerPort: 52834
        hostPort: 52834
        protocol: TCP
      - containerPort: 30080 
        hostPort: 30080
        protocol: TCP
